# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\softs_study\projects\tianda_employee\employee.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1107, 781)
        MainWindow.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.export_2 = QtWidgets.QPushButton(self.centralWidget)
        self.export_2.setGeometry(QtCore.QRect(880, 710, 131, 31))
        self.export_2.setObjectName("export_2")
        self.dateEdit = QtWidgets.QDateEdit(self.centralWidget)
        self.dateEdit.setGeometry(QtCore.QRect(610, 20, 121, 21))
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2017, 7, 2), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setCalendarPopup(False)
        self.dateEdit.setTimeSpec(QtCore.Qt.TimeZone)
        self.dateEdit.setObjectName("dateEdit")
        self.pushButton_timeEnsure = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_timeEnsure.setGeometry(QtCore.QRect(770, 20, 75, 23))
        self.pushButton_timeEnsure.setObjectName("pushButton_timeEnsure")
        self.label_weekcount = QtWidgets.QLabel(self.centralWidget)
        self.label_weekcount.setGeometry(QtCore.QRect(300, 10, 211, 41))
        self.label_weekcount.setObjectName("label_weekcount")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 90, 1061, 601))
        self.tabWidget.setStyleSheet("background-color: rgb(255, 250, 238);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget_thisweek = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_thisweek.setGeometry(QtCore.QRect(0, 0, 1061, 581))
        self.tableWidget_thisweek.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_thisweek.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget_thisweek.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget_thisweek.setObjectName("tableWidget_thisweek")
        self.tableWidget_thisweek.setColumnCount(8)
        self.tableWidget_thisweek.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thisweek.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thisweek.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thisweek.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thisweek.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thisweek.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thisweek.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thisweek.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thisweek.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thisweek.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thisweek.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thisweek.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thisweek.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thisweek.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thisweek.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thisweek.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thisweek.setItem(4, 7, item)
        self.tableWidget_thisweek.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_thisweek.horizontalHeader().setHighlightSections(True)
        self.tableWidget_thisweek.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_thisweek.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_thisweek.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget_thisweek.verticalHeader().setStretchLastSection(False)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_lastweek = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_lastweek.setGeometry(QtCore.QRect(0, 0, 1061, 581))
        self.tableWidget_lastweek.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_lastweek.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget_lastweek.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_lastweek.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget_lastweek.setObjectName("tableWidget_lastweek")
        self.tableWidget_lastweek.setColumnCount(8)
        self.tableWidget_lastweek.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lastweek.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lastweek.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lastweek.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lastweek.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lastweek.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lastweek.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lastweek.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lastweek.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lastweek.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lastweek.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lastweek.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lastweek.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lastweek.setHorizontalHeaderItem(7, item)
        self.tableWidget_lastweek.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_lastweek.horizontalHeader().setHighlightSections(True)
        self.tableWidget_lastweek.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_lastweek.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_lastweek.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget_lastweek.verticalHeader().setStretchLastSection(False)
        self.tabWidget.addTab(self.tab_2, "")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(620, 50, 201, 21))
        self.label.setObjectName("label")
        self.pushButton_submint = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_submint.setGeometry(QtCore.QRect(714, 712, 121, 31))
        self.pushButton_submint.setObjectName("pushButton_submint")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(480, 710, 201, 41))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1107, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menuBar)
        self.actionleave = QtWidgets.QAction(MainWindow)
        self.actionleave.setObjectName("actionleave")
        self.actionexport = QtWidgets.QAction(MainWindow)
        self.actionexport.setObjectName("actionexport")
        self.actionexit = QtWidgets.QAction(MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.action_xinyuangong = QtWidgets.QAction(MainWindow)
        self.action_xinyuangong.setObjectName("action_xinyuangong")
        self.actionleave_2 = QtWidgets.QAction(MainWindow)
        self.actionleave_2.setObjectName("actionleave_2")
        self.actionchange_info = QtWidgets.QAction(MainWindow)
        self.actionchange_info.setObjectName("actionchange_info")
        self.actionabout = QtWidgets.QAction(MainWindow)
        self.actionabout.setObjectName("actionabout")
        self.actionhelp = QtWidgets.QAction(MainWindow)
        self.actionhelp.setObjectName("actionhelp")
        self.menu.addAction(self.actionleave)
        self.menu.addAction(self.actionexport)
        self.menu.addAction(self.actionexit)
        self.menu_2.addAction(self.action_xinyuangong)
        self.menu_2.addAction(self.actionleave_2)
        self.menu_2.addAction(self.actionchange_info)
        self.menu_3.addAction(self.actionabout)
        self.menu_3.addAction(self.actionhelp)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.export_2.setText(_translate("MainWindow", "导出当前工资单"))
        self.pushButton_timeEnsure.setText(_translate("MainWindow", "确认"))
        self.label_weekcount.setText(_translate("MainWindow", "今天是2017年10月20日 本年度第x周"))
        self.tableWidget_thisweek.setSortingEnabled(True)
        item = self.tableWidget_thisweek.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_thisweek.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_thisweek.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_thisweek.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_thisweek.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_thisweek.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "账号"))
        item = self.tableWidget_thisweek.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "姓名"))
        item = self.tableWidget_thisweek.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "动态权益"))
        item = self.tableWidget_thisweek.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "手续费"))
        item = self.tableWidget_thisweek.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "扣款"))
        item = self.tableWidget_thisweek.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "备注"))
        item = self.tableWidget_thisweek.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "结算薪水"))
        item = self.tableWidget_thisweek.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "发放"))
        __sortingEnabled = self.tableWidget_thisweek.isSortingEnabled()
        self.tableWidget_thisweek.setSortingEnabled(False)
        item = self.tableWidget_thisweek.item(0, 0)
        item.setText(_translate("MainWindow", "测试位置1"))
        item = self.tableWidget_thisweek.item(1, 1)
        item.setText(_translate("MainWindow", "测试位置2"))
        item = self.tableWidget_thisweek.item(4, 7)
        item.setText(_translate("MainWindow", "测试位置3"))
        self.tableWidget_thisweek.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "本周"))
        self.tableWidget_lastweek.setSortingEnabled(True)
        item = self.tableWidget_lastweek.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_lastweek.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_lastweek.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_lastweek.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_lastweek.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_lastweek.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "账号"))
        item = self.tableWidget_lastweek.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "姓名"))
        item = self.tableWidget_lastweek.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "应发"))
        item = self.tableWidget_lastweek.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "扣款"))
        item = self.tableWidget_lastweek.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "备注"))
        item = self.tableWidget_lastweek.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "结算薪水"))
        item = self.tableWidget_lastweek.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "结算"))
        item = self.tableWidget_lastweek.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "发放"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "上一周"))
        self.label.setText(_translate("MainWindow", "当前选择为本年度第x-2周"))
        self.pushButton_submint.setText(_translate("MainWindow", "提交/修改"))
        self.label_2.setText(_translate("MainWindow", "您尚未提交本周薪资：RED；您已提交本周薪资"))
        self.menu.setTitle(_translate("MainWindow", "程序"))
        self.menu_2.setTitle(_translate("MainWindow", "员工"))
        self.menu_3.setTitle(_translate("MainWindow", "关于"))
        self.actionleave.setText(_translate("MainWindow", "import"))
        self.actionexport.setText(_translate("MainWindow", "export"))
        self.actionexit.setText(_translate("MainWindow", "exit"))
        self.action_xinyuangong.setText(_translate("MainWindow", "xinyuangong"))
        self.actionleave_2.setText(_translate("MainWindow", "leave"))
        self.actionchange_info.setText(_translate("MainWindow", "change_info"))
        self.actionabout.setText(_translate("MainWindow", "about"))
        self.actionhelp.setText(_translate("MainWindow", "help"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

